# Homework 03

## Due Thursday, February 18th

### 1. Vector manipulation

Create a vector of zeros of size 10 but have the fifth value be 1.

In [148]:
import numpy as np
vector1=np.zeros((10,),dtype=np.float32)
vector1[4]=1
vector1

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

### 2. Vector range

Create a vector with values ranging from 10 to 49, inclusive.

In [150]:
vector2=np.arange(10,50,)
vector2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element. The API should be

    return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed

Include this (or an equivalent description) in the function's docstring.

In [151]:
def reverse(x):
    """return a 1D vector with the elements reversed

      Input
      -----
          x: 1D array

      Output
      ------
          res: 1D array, with the elements of `x` reversed 
   """
    y=x[::-1]
    return y


reverse(vector2)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 4. Find indices of non-zero elements

Write a function `find_nonzero(x)` that finds the indices of non-zero elements, with an API like

    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices

Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

In [156]:
def find_nonzero(x):
    """
    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices
    """
    ind =np.where( x != 0)[0]
    return ind
    
a=np.array([1,2,0,0,4,0])
find_nonzero(a)

array([0, 1, 4], dtype=int64)

### 5. Array with random values

Create a 3x3x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.

In [157]:
random1=np.random.randn(3,3,3)
random1

array([[[ 2.18304296, -1.41108039,  0.58071511],
        [-1.07258975, -0.79258867,  1.17618694],
        [-1.51543363, -0.497753  , -0.70716081]],

       [[-0.73717546,  0.54745933,  1.68391719],
        [ 0.97551244,  0.22532905,  2.56219787],
        [-0.18905437,  0.70143372, -1.69002723]],

       [[-1.01850341, -0.52176261,  0.96137448],
        [ 1.96921242,  0.59988978, -0.14844841],
        [ 1.65740161,  0.30238578,  1.99298392]]])

### 6. Operations on an array with random values

Create a 10x10 array with random values. Find 
- the minimum value of the 2nd row
- the maximum value of the 4th column

In [159]:
random2=np.random.random(100).reshape(10,10)
print('10*10 random array\n',random2,'\n\n')
imin2r=np.argmin(random2,axis=1)[1]
imax4c=np.argmax(random2,axis=0)[3]
print('The minimum value of the 2nd row: ',random2[1,imin2r],'\n\nThe maximum value of the 4th column: ',random2[imax4c,3])


10*10 random array
 [[ 0.46590232  0.33208728  0.50747912  0.110343    0.18056701  0.21873213
   0.81593707  0.58131441  0.94273602  0.48605977]
 [ 0.66641795  0.30835335  0.33236214  0.7496117   0.69254583  0.27169548
   0.64036689  0.85432493  0.39807297  0.40247536]
 [ 0.87449921  0.87747933  0.43697799  0.2247336   0.02751467  0.01061035
   0.42150257  0.87813619  0.71128959  0.29462183]
 [ 0.08944215  0.47381495  0.78378459  0.73475183  0.74188956  0.63128443
   0.27158286  0.61668596  0.95193851  0.93891267]
 [ 0.08251751  0.03682032  0.61350627  0.21369612  0.10210372  0.82296007
   0.53808638  0.8881029   0.83486885  0.27303943]
 [ 0.67540271  0.57297307  0.82813937  0.38427474  0.86062924  0.22204234
   0.69746596  0.51609716  0.24828152  0.78984485]
 [ 0.45124471  0.07001279  0.19176545  0.91603146  0.56668436  0.10178281
   0.30285775  0.93282697  0.55060787  0.52565367]
 [ 0.78875719  0.67315925  0.49925192  0.73406427  0.50035351  0.65682205
   0.32266669  0.63104202  0.71

### 7. Vector without end points

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [160]:
vector3=np.linspace(0, 1, 11,endpoint=False)[1:]
vector3

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

### 8. Sorted random vector

Create a random vector of size 10, then sort it.

In [161]:
vector4 = np.random.random(10)
print('Original vector: ',vector4, '\n\nSorted vector: ',np.sort(vector4))



Original vector:  [ 0.87530531  0.83860241  0.02333555  0.7238699   0.38296831  0.1935914
  0.60924311  0.49226365  0.45724848  0.43904552] 

Sorted vector:  [ 0.02333555  0.1935914   0.38296831  0.43904552  0.45724848  0.49226365
  0.60924311  0.7238699   0.83860241  0.87530531]


### 9. Test for array equality

Write a function `is_equal(A, B)` that compare two arrays `A` and `B` and checks to see if they are equal. 

    return True if two arrays are the same shape and all the elements are equal.
    
    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.

The arrays count as equal if they are the same shape and all elements in the array are equal.

In [164]:
###################
#####Method 1######
###################

def is_equal(A,B):
    """
    return True if two arrays are the same shape and all the elements are equal.

    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.
    """
    a=A.shape
    b=B.shape
    if a!=b:
        c=False
        return c
    else:
        x=(A==B).all()
        return x

##################
#### Check #######
#################


# a=np.array([1,2,3,5])
# b=np.array([1,2,3,4,5])
a=np.arange(10,50,).reshape(4,10)
b=np.linspace(10, 49, 40).reshape(4,10)
is_equal(a, b)

True

In [165]:
###################
#####Method 2######
###################


def is_equal(A,B):
    """
    return True if two arrays are the same shape and all the elements are equal.

    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.
    """

    x=np.array_equal(A,B)
    return x


a=np.arange(10,50,).reshape(4,10)
b=np.linspace(10.1, 49, 40).reshape(5,8)
is_equal(a, b)

False

### 10. Subtract the row mean from rows of a matrix

Create a matrix. Then subtract the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [166]:
arr1=np.arange(25).reshape(5,5)
print('The original matrix is: \n',arr1)
mean1=arr1.mean(axis=1)
print('\nThe means of each row are: \n',mean1)
mean2=mean1[:, np.newaxis]
arr2=arr1-mean2
print('\nSubtract the mean of each row of the matrix from the respective row:\n',arr2)



The original matrix is: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The means of each row are: 
 [  2.   7.  12.  17.  22.]

Subtract the mean of each row of the matrix from the respective row:
 [[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


### 11. Multiply arrays

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [167]:
arr1=np.arange(75).reshape(5,5,3)
print('An array of dimensions(5,5,3):\n',arr1)
arr2=np.arange(25).reshape(5,5)
print('\nAn array of dimensions(5,5):\n',arr2)
arr3=np.expand_dims(arr2, axis=2)
arr4=arr1*arr3
print('\nMultiply an array of dimensions(5,5,3) with an array with dimensions (5,5).:\n',arr4)


arr5=np.arange(75).reshape(3,5,5)
print('\n\nAn array of dimensions(3,5,5):\n',arr5)
arr6=np.arange(25).reshape(5,5)
print('\n\nAn array of dimensions(5,5):\n',arr6)
arr7=np.expand_dims(arr6,axis=0)
arr8=arr5*arr7
print('Multiply an array of dimensions(3,5,5) with an array of dimensions(5,5):\n',arr8)



An array of dimensions(5,5,3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]

An array of dimensions(5,5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Multiply an array of dimensions(5,5,3) with an array with dimensions (5,5).:
 [[[   0    0    0]
  [   3    4    5]
  [  12   14   16]
  [  27   30   33]
  [  48   52   56]]

 [[  75   80   85]
  [ 108  114  120]
  [ 147  154  161]
  [ 192  200  208]
  [ 243  252  261]]

 [[ 300  310  320]
  [ 363  374  385]
  [ 432  444  456]
  [ 507  520  533]
  [ 588  602  616]]

 [[ 675  690  705]
  [ 768  784  800]
  [ 867  884  901]
  [ 972  990 1008]
  [1083 1102 1121]]

 [[1200 1220 1240]
  [1323 1344 1365]
  [145

### 12. Creating a new array

Starting with an array

    Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
    
Generate an array 

    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [168]:
from numpy.lib import stride_tricks 
Z=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
Z.strides
R=stride_tricks.as_strided(Z,shape=(11,4),strides=(Z.strides[0],Z.strides[0]))
print(R)



[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 13. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is

    Return equivalent polar coordinates of specified cartesian points.
    
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively


In [171]:
def cart2polar(xy):
    """
    Return equivalent polar coordinates of specified cartesian points.

    Inputs:
    xy: array
         Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
    rp: array
        Nx2 array of polar coordinates, with columns radius and angle respectively
    """

    rp=np.zeros(xy.shape)
    rp[:,1]=np.arctan2(xy[:,1],xy[:,0])
    rp[:,0]=np.sqrt(xy[:,0]**2+xy[:,1]**2)

    return rp




#############
### Check ###
#############

a=np.array([[1,1],[-1,1],[-1,-1],[1,-1]])
cart2polar(a)

array([[ 1.41421356,  0.78539816],
       [ 1.41421356,  2.35619449],
       [ 1.41421356, -2.35619449],
       [ 1.41421356, -0.78539816]])

### 14. Compute and time for loops and array operations.

Calculate the time it takes to do what we did in class

    a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
    b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
    sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

and the time required for doing the same operation with a series of 4 `for` loops, one for each dimension of the arrays. Compare the times by calculating a ratio.

In [178]:
import time

############################
##### Array operation ######
############################

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

t_start1 = time.time()
# time.sleep(0.000000000000000001)
sol1 = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.
t_stop1 = time.time()
t1=t_stop1-t_start1
print(t_start1)
print(t_stop1)
print('{:6.20f} seconds have passed using array operation.'.format(t1))

############################
######## For Loops #########
############################

t_start2 = time.time()
c = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
d = np.random.rand(4, 8, 16, 2) # a 4D array using random numbers
i1,i2,i3,i4=0,0,0,0
sol2 = np.empty((4,8,16,2), dtype=np.float)
for i1 in range(4):
        for i2 in range(8):
            for i3 in range(16):
                for i4 in range(2):
                    sol2[i1,i2,i3,i4] = c[i1,i2,i3,i4] * d[i1,i2,i3,i4]
t_stop2 = time.time()
t2=t_stop2-t_start2
print('{:6.20f} seconds have passed using for loops.'.format(t2))

#######################
######## Ratio #######
#######################

print('The ration(Array Operation/For Loops) is {:6.4f}.'.format(t1/t2))
#print(sol1)
#print(sol2)


1455856978.2476082
1455856978.2476082
0.00000000000000000000 seconds have passed using array operation.
0.00500035285949707031 seconds have passed using for loops.
The ration(Array Operation/For Loops) is 0.0000.


### 15. Fix the code

This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. Write out what you changed to make it work and why it needed to be changed.

In [179]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa=aa/4.              # change aa /= 4. into aa=aa/4. the origianl code will change the value of the array
    a[:2, :] -= aa
    b=np.expand_dims(b, axis=2)  # add a column for array broadcasting
    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

### 16. Calculate components of a vector

Read in file `data/burl1h2010.txt`. This file gives a bunch of data from a wind station. In particular, read in the wind direction, `WDIR`, and wind speed, `WSPD`. Then, write a function that calculates and returns the `u` and `v` components of this wind vector, which point along the x- and y-axes.

The function should have the following basic functionality:

    Take in vector and return components.
    
    Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude
        
    Returns:
        u: x component of vector
        v: y component of vector


In [185]:
from math import pi
data = np.loadtxt('burl1h2010.txt', comments='#')
vdir=data[:,5]
vspd=data[:,6]

def calculate(vdir,vspd):
    """
    Take in vector and return components.

    Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

    Returns:
    u: x component of vector
    v: y component of vector
    """
    u=np.zeros(vdir.shape)
    v=np.zeros(vdir.shape)
    u=np.cos(vdir/180*pi)*vspd
    v=np.sin(vdir/180*pi)*vspd
    return u,v


calculate(vdir,vspd)

    

(array([ -2.08397511,  -1.96070053,  -2.12119911, ...,  -9.56084447,
        -10.50707636,  -8.83345912]),
 array([ 2.1580194 ,  3.01921404,  2.52794666, ...,  6.208885  ,
         5.5867116 ,  5.1       ]))

### 17. (Grad) Write and use a class

Consider one of the data files located in `python4geosciences/data/MCH/`. Write a class, `dataclass`, to store some of the information in the file. The class should:

* be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values found in the file;
* contain a method, `salt_mean`, which returns the mean of the salinity;
* contain a method, `temp_max`, which returns the maximum value of the temperature values.

Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. Instead, write a loop which loops through the file names, reads in the necessary data, calls `dataclass` to store the data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should have a list of all of the class instances, one for each data file. As usage examples, if your list of data objects is called `wind`, you should be able to access the temperatures from the 3rd file that is read in with

    wind[2].temp

and you should be able to calculate the mean salinity of the final file with 

    wind[-1].salt_mean()

Hint: Check out the package `glob` for reading in file names with a wild card. 

In [186]:
#######################
##### Create Class ####
#######################

class dataclass(object):
    
    def __init__(self, name, temp, sal):
        self.name = name
        self.temp = temp
        self.sal = sal
    
    def salt_mean(self):
        'Returns the mean of the salinity'
        return self.sal.mean(axis=0)
    
    def temp_max(self):
        'Returns the maximum value of the temperature values'
        return self.temp.max(axis=0)
    

##########################
###### Reading File ######   
#### Creating Instance ###
##########################

import glob
import numpy as np


wind= []

for filename in glob.glob("D:/OCNG689/python4geosciences/data/MCH/*.cnv2"):
    filename1=filename.split('\\')[-1][:-5]
    temperature=[]
    salinity=[]
    with open(filename) as f:
        for _ in range(1,58):
            next(f)
        for line in f.readlines():
            data=line.split()
            temperature.append(float(data[2]))
            salinity.append(float(data[5]))
        temparry=np.array(temperature)   
        salarry=np.array(salinity)
    wind.append(dataclass(filename1, temparry, salarry ))
    


#####################
##### Validation ####
#####################

print(wind[2].temp)
print(wind[2].sal)
print(wind[2].name)
wind[-1].salt_mean()



    



[ 21.2128  21.2149  21.2177  21.219   21.2165  21.2331  21.3468  21.4867
  21.526   21.5914  21.6244  21.6219  21.6295  21.6204  21.6003  21.5912
  21.4888  21.3504  21.2779  21.343   21.4117  21.4415  21.441   21.3959
  21.3208  21.2352  21.1793  21.1591  21.1479  21.1501  21.1435  21.1413
  21.1385  21.1377  21.1369]
[ 23.7654  23.765   23.7652  23.7653  23.7632  23.8045  24.5297  25.5772
  25.8547  26.3508  26.6671  26.9786  27.1707  27.2937  27.4737  27.7143
  28.9596  30.9501  33.1455  34.1195  34.656   35.1729  35.7207  35.9413
  36.0207  36.0671  36.0935  36.1033  36.1087  36.0834  36.0837  36.08
  36.095   36.0965  36.1113]
m1002a


35.828874999999996

### 18. (Grad) Running mean

Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.

Do not use the `pandas` package or the function `convolve`; instead, use a loop. Use the following API for your function:

    Return the running average of a vector, with averaging window of size N.
    
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
    Outputs:
        out: Vector of running-averaged values; same size as vec


In [243]:
def running_mean(vec, N):
    """
    Return the running average of a vector, with averaging window of size N.

    Inputs:
    vec: Input vector
    N (int): Averaging window size, or number of elements to include in mean on either side of each element.

    Outputs:
    out: Vector of running-averaged values; same size as vec
    """
    out = np.zeros_like(vec)
    size=vec.size
    print('size',size)
    if (N==0):
        return vec
    else:
        for i in range(0,N):
            out[i]=vec[i]
        for i in range(N,size-N):
            arr1=np.zeros(2*N+1)
            m=0
            for n in range(i-N,i+N+1):
                arr1[m]=vec[n]
                m+=1
            out[i]=arr1.mean()
        for i in range(size-N,size):
            out[i]=vec[i]
        
    return out
    

###############
### Check ####
##############

a=np.array([1.,9.,9.,1.,0.,6.,2.,7.,3.,2.,1.,1.])
running_mean(a, 3)  

size 12


array([ 1.        ,  9.        ,  9.        ,  4.        ,  4.85714286,
        4.        ,  3.        ,  3.        ,  3.14285714,  2.        ,
        1.        ,  1.        ])